# Generated by Django 5.1.4 on 2025-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/profile-img/default-img.png', upload_to='media/profile-img/'),
        ),
    ]
